#PBS -l nodes=1:ppn=24
#PBS -l feature=rhel7
#PBS -l walltime=48:00:00
#PBS -A open
#PBS -o YOUR_PATH/LOG/${kp}-${kn}-${maxtime}-${seed}.log
#PBS -j oe
#PBS -l mem=100gb
cd YOUR_PATH

echo " "
echo " "
echo "Job started on `hostname` at `date`"
echo " "

module use YOUR_PATH/default/sw/modules
module load gurobi/9.1.0
module load r/3.6.1
module load gcc/7.3.1
module load git
module load julia/1.3.1
julia sfsod_logreg.jl $kp $kn $maxtime $seed

echo " "
echo "Job Ended at `date`"
echo " "
